# Generated by Django 6.0.2 on 2026-03-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(help_text='Full name of the applicant.', max_length=255, verbose_name='Applicant Name')),
                ('country', models.CharField(help_text='Country of residence.', max_length=255, verbose_name='Country')),
                ('email', models.EmailField(max_length=280, verbose_name='Email Address')),
                ('phone', models.CharField(help_text='Contact number of applicant.', max_length=20, verbose_name='Phone Number')),
                ('beneficiary_name', models.CharField(max_length=255, verbose_name='Name of Beneficiary')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Bank Name')),
                ('bank_address', models.CharField(max_length=255, verbose_name='Bank Address Line 1')),
                ('account_number', models.CharField(max_length=100, verbose_name='Account Number')),
                ('iban_number', models.CharField(max_length=100, verbose_name='IBAN Number')),
                ('swift_code', models.CharField(max_length=50, verbose_name='SWIFT Code')),
                ('correspondent_account_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Correspondent Bank Account Number')),
                ('correspondent_bank_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Correspondent Bank Address')),
                ('declaration_name', models.CharField(help_text='Name written in declaration section.', max_length=255, verbose_name='Declaration Name')),
                ('declaration_date', models.DateField(verbose_name='Declaration Date')),
                ('signature', models.CharField(max_length=255, verbose_name='Signature')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Bank Account Information',
                'verbose_name_plural': 'Bank Account Informations',
                'ordering': ['-created_at'],
            },
        ),
    ]
