# Generated by Django 6.0.2 on 2026-03-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon_ico', models.FileField(blank=True, help_text='Recommended size: 16x16, 32x32 (ICO format).', null=True, upload_to='favicon/', verbose_name='Favicon ICO (.ico)')),
                ('favicon_16', models.FileField(blank=True, help_text='Recommended size: (16x16).', null=True, upload_to='favicon/', verbose_name='Favicon 16x16')),
                ('favicon_16_width', models.IntegerField(blank=True, null=True, verbose_name='Favicon 16 Width')),
                ('favicon_16_height', models.IntegerField(blank=True, null=True, verbose_name='Favicon 16 Height')),
                ('favicon_32', models.FileField(blank=True, help_text='Recommended size: (32x32).', null=True, upload_to='favicon/', verbose_name='Favicon 32x32')),
                ('favicon_32_width', models.IntegerField(blank=True, null=True, verbose_name='Favicon 32 Width')),
                ('favicon_32_height', models.IntegerField(blank=True, null=True, verbose_name='Favicon 32 Height')),
                ('apple_touch_icon', models.FileField(blank=True, help_text='Recommended apple touch icon size: (180x180).', null=True, upload_to='favicon/', verbose_name='Apple Touch Icon (180x180)')),
                ('apple_width', models.IntegerField(blank=True, null=True, verbose_name='Favicon Apple 32 Width')),
                ('apple_height', models.IntegerField(blank=True, null=True, verbose_name='Favicon Apple 180 Height')),
                ('android_192', models.FileField(blank=True, help_text='Recommended android icon size: (192x192).', null=True, upload_to='favicon/', verbose_name='Android 192x192')),
                ('android_192_width', models.IntegerField(blank=True, null=True, verbose_name='Favicon ApAndroidple 192 Width')),
                ('android_192_height', models.IntegerField(blank=True, null=True, verbose_name='Favicon Android 192 Height')),
                ('android_512', models.FileField(blank=True, help_text='Recommended android icon size: (512x512) (PWA).', null=True, upload_to='favicon/', verbose_name='Android 512x512 (PWA)')),
                ('android_512_width', models.IntegerField(blank=True, null=True, verbose_name='Favicon Android 512 Width')),
                ('android_512_height', models.IntegerField(blank=True, null=True, verbose_name='Favicon Android 512 Height')),
                ('ms_tile_icon', models.FileField(blank=True, help_text='Recommended microsoft icon size: (144x144).', null=True, upload_to='favicon/', verbose_name='Microsoft Tile (144x144)')),
                ('ms_width', models.IntegerField(blank=True, null=True, verbose_name='Favicon Microsoft 144 Height')),
                ('ms_height', models.IntegerField(blank=True, null=True, verbose_name='Favicon Microsoft 144 Height')),
            ],
            options={
                'verbose_name': 'Favicon',
                'verbose_name_plural': 'Favicon',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='logo/', verbose_name='Logo')),
                ('alt', models.CharField(blank=True, max_length=280, null=True, verbose_name='Logo Alt')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Width')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Height')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logo',
                'ordering': ['-id'],
            },
        ),
    ]
