# Generated by Django 6.0.2 on 2026-03-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_of_duty', models.CharField(choices=[('TOURNAMENT', 'Tournament'), ('SEMINAR', 'Seminar'), ('EVENT', 'Event'), ('OTHERS', 'Others')], help_text='Select the purpose of travel.', max_length=20, verbose_name='Nature of Duty')),
                ('event_name', models.CharField(help_text='Name of the tournament, seminar or event.', max_length=255, verbose_name='Event Name')),
                ('name', models.CharField(max_length=255, verbose_name='Your Full Name')),
                ('designation', models.CharField(max_length=255, verbose_name='Designation / Position')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nationality')),
                ('venue', models.CharField(help_text='Location where the event was held.', max_length=255, verbose_name='Venue')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('departure_date', models.DateField(verbose_name='Departure Date')),
                ('return_date', models.DateField(verbose_name='Return Date')),
                ('travelling_date', models.DateField(verbose_name='Travelling Date')),
                ('travel_from', models.CharField(max_length=255, verbose_name='Travel From')),
                ('travel_to', models.CharField(max_length=255, verbose_name='Travel To')),
                ('ticket_cost', models.DecimalField(decimal_places=2, help_text='Airfare ticket cost in local currency.', max_digits=10, verbose_name='Ticket Cost')),
                ('amount_local_currency', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount in Local Currency')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount in USD')),
                ('exchange_rate', models.DecimalField(decimal_places=4, help_text='1 USD equals how much local currency.', max_digits=10, verbose_name='Exchange Rate')),
                ('number_of_days', models.PositiveIntegerField(verbose_name='Number of Days')),
                ('daily_calculation', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Daily Allowance (Per Day USD)')),
                ('daily_total_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Daily Allowance (USD)')),
                ('incidental_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Incidental Expense 1 Description')),
                ('incidental_1_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Incidental Expense 1 (USD)')),
                ('incidental_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Incidental Expense 2 Description')),
                ('incidental_2_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Incidental Expense 2 (USD)')),
                ('total_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total (USD)')),
                ('other_total_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Other Expenses Total (USD)')),
                ('grand_total_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Grand Total (USD)')),
                ('attachment', models.FileField(blank=True, help_text='Upload supporting documents (tickets, receipts etc.).', null=True, upload_to='travel_claims/', verbose_name='Attachment')),
                ('claimed_by', models.CharField(max_length=255, verbose_name='Claimed By')),
                ('date', models.DateField(help_text='Enter the date on which this travel claim is being submitted.', verbose_name='Claim Submission Date')),
                ('signature', models.CharField(help_text='Enter your full name as signature or type your digital signature here.', max_length=255, verbose_name='Signature')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Travel Claim',
                'verbose_name_plural': 'Travel Claims',
                'ordering': ['-created_at'],
            },
        ),
    ]
