# Generated by Django 6.0.2 on 2026-03-16 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_claim', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TravelClaim',
        ),
    ]
